# Neo4j 5 Enterprise - Configuração
# Montado como volume para evitar problemas com variáveis de ambiente

server.memory.heap.initial_size=2G
server.memory.heap.max_size=4G
server.memory.pagecache.size=2G

dbms.tx_log.rotation.retention_policy=100M size, 7 days
dbms.security.procedures.unrestricted=apoc.*

dbms.connector.bolt.advertised_address=neo4j:7687
dbms.connector.http.advertised_address=neo4j:7474

# APOC
dbms.security.procedures.allowlist=apoc.*
